
CC = gcc

CFLAGS = -Wall -Wextra -Werror

SRC = get_next_line.c

OBJ_FILES = $(SRC:.c=.o)
OBJ_PATH = ./obj/
OBJ = $(addprefix $(OBJ_PATH), $(OBJ_FILES))

VPATH = src:include

IFLAGS = -I include
HEADERS = get_next_line.h

